src/objects/h_Production_Org_Ids__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchy setting for storing a Production Org Id</description>
    <fields>
        <fullName>Org_Id_18_char__c</fullName>
        <description>This is a string representation of a Salesforce Org Id</description>
        <inlineHelpText>18 char Org Id</inlineHelpText>
        <label>Org Id 18 char</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Production Org Ids</label>
</CustomObject>

src/classes/instanceCheck.cls
public with sharing class instanceCheck {
  @AuraEnabled
  public static boolean getIsProduction(){
    boolean returnBool;
    h_Production_Org_Ids__c mySetting = new h_Production_Org_Ids__c();  //Create a new instance of the Custom Setting
    mySetting = h_Production_Org_Ids__c.getOrgDefaults();               //get the Org default dataset for our Production Org
    string currentOrgId = UserInfo.getOrganizationId();                 //get the current Org Id from the UserInfo Class
    if(currentOrgId == mySetting.Org_Id_18_char__c){                    //compare the two Org Ids...
      returnBool = true;                                                //if True, We are in production, use production behaviour 
    } else {                                                            //if False...
      returnBool = false;                                               //then we are in a Sandbox, use sandbox behaviour
    }
    system.debug('isProductionOrg = ' + returnBool);                    //handy debug statement for an exec anon demo
    return returnBool;
  }
}