src/objects/License__c.object
<CustomObject>
    <description>This Custom sObject represents a License</description>
    <fields>
        <fullName>isIssued__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the License is Issued</description>
        <label>Is Issued</label>
        <type>Checkbox</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>LIC{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/thresholds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to set numerical limits</description>
    <fields>
        <fullName>Adjustment_Factor__c</fullName>
        <description>Use to set the amount the limit is to be adjusted</description>
        <inlineHelpText>Set the Adjustment Factor</inlineHelpText>
        <label>Adjustment Factor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>High_Limit__c</fullName>
        <description>Used to set a max limit</description>
        <inlineHelpText>Set the maximum limit threshold</inlineHelpText>
        <label>High Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Limit_Default_Value__c</fullName>
        <description>This is the default value used when resetting the Low_Limit__c</description>
        <label>Low Limit Default Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low_Limit__c</fullName>
        <description>Used to store the lower limit threshold</description>
        <inlineHelpText>Set the lower limit for action</inlineHelpText>
        <label>Low Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Thresholds</label>
</CustomObject>

src/classes/thresholdsChecks.cls
public class thresholdsChecks {
    
    public thresholds__c checkThresholds(){
        Integer availableLicenses = [SELECT count() FROM License__c WHERE isIssued__c = false];
        thresholds__c thresholds = thresholds__c.getInstance('Licenses');
        if(availableLicenses <= thresholds.Low_Limit__c){ //Adjust limit DOWN, and create a Case
            double newLowLimit = math.floor(thresholds.Low_Limit__c/thresholds.Adjustment_Factor__c);
            thresholds.Low_Limit__c = (integer)newLowLimit;
            update thresholds; //Adjust limit DOWN
            case createdCase = createLowLimitCase(availableLicenses, thresholds); //Create a Case
        } else if(availableLicenses >= thresholds.High_Limit__c &&
            thresholds.Low_Limit__c != thresholds.Low_Limit_Default_Value__c){ //Adjust the limit UP
            thresholds.Low_Limit__c = thresholds.Low_Limit_Default_Value__c;
            update thresholds; //Adjust the limit UP
        }
        return thresholds ;
    }
    
    public Case createLowLimitCase(integer availableLicenses, thresholds__c newSettings){
        Case LowLimitCase = new Case();
        LowLimitCase.Description = 'The number of availableLicenses is ' + availableLicenses + '\r\n' +
            'The warning threshold has been adjusted to : ' + newSettings.Low_Limit__c;
        LowLimitCase.Origin = 'Web';
        LowLimitCase.Priority='Critical';
        LowLimitCase.Status='New';
        LowLimitCase.Type='Threshold';
        insert LowLimitCase;
        return LowLimitCase;
    }
}